#!/bin/sh

set -e

_ask() {
	printf "%s: " "$1"
	read -r "$2"
}

_ask "Config filename (tun0)" NAME
NAME=${NAME:-tun0}

if [ -f /etc/glorytun/"$NAME" ]; then
	echo "This config already exit!"
	exit 1
fi

_ask "Server ip (enter for server conf)" HOST

_ask "Server key (enter to generate a new one)" KEY
if [ -z "$KEY" ]; then
	KEY=$(glorytun keygen)
	echo "Your new key: $KEY"
fi

# install files

mkdir -p /etc/glorytun
env | grep 'TABLE=\|HOST=' > /etc/glorytun/"$NAME"
( umask 077; echo "$KEY" > /etc/glorytun/"$NAME".key )

# start services

_ask "Start glorytun now ? (enter to skip)" START
case "$START" in y*|Y*)
	systemctl daemon-reload
	systemctl start systemd-networkd
	systemctl start glorytun@"$NAME" ;;
esac
